spring.application.name=order-service
server.port=8081

spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/order_db
spring.datasource.username=order_user
spring.datasource.password=order_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.url=jdbc:postgresql://127.0.0.1:5432/order_db
spring.flyway.user=order_user
spring.flyway.password=order_password

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when-authorized